name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: run main.py
      run: |
        python main.py
        LAST_VERSION=$(jq -r '.version' last_ldn_info.json)
        echo "last_version=${LAST_VERSION}" >> $GITHUB_ENV
        if [ $(ls download | wc -l) != "1" ]; then echo "file_updated=true" >> $GITHUB_ENV; fi
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      if: ${{ env.file_updated }} == "true"
      with:
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'update'
        add: '*.json'
        tag: ${{ env.last_version }}
    - name: Release
      uses: softprops/action-gh-release@v1
      if: ${{ env.file_updated }} == "true"
      with:
#        draft: true
        name: ${{ env.last_version }}
        tag_name: ${{ env.last_version }}
        body: LDN archive of ${{ env.last_version }}
        files: |
          download/*.zip
